using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace Wimm.Machines.Tpip3.Import
{
    /// <summary>
    /// TPJT3.dll Binding generated by P/Invoke Interop Assistant
    /// </summary>
    public class TPJT3
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct OUT_DT_STR
        {

            /// unsigned short
            public ushort d_out;

            /// short
            public short nouse1;

            /// short[4]
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4, ArraySubType = UnmanagedType.I2)]
            public short[] PWM;

            /// short[16]
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16, ArraySubType = UnmanagedType.I2)]
            public short[] PWM2;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct INP_DT_STR
        {

            /// unsigned short
            public ushort b_ptn;

            /// unsigned short[8]
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8, ArraySubType = UnmanagedType.U2)]
            public ushort[] AI;

            /// short[4]
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4, ArraySubType = UnmanagedType.I2)]
            public short[] PI;

            /// unsigned short
            public ushort batt;

            /// short
            public short PI1;

            /// short
            public short PI2;

            /// unsigned short
            public ushort DI;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct INP_PI_DT_STR
        {

            /// unsigned int
            public uint PI01_z;

            /// int
            public int PI01_ab;

            /// unsigned int
            public uint PI02_z;

            /// int
            public int PI02_ab;

            /// unsigned int
            public uint PI03_z;

            /// int
            public int PI03_ab;

            /// unsigned int
            public uint PI04_z;

            /// int
            public int PI04_ab;
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct CanMessage
        {

            /// unsigned char
            public byte flg;

            /// unsigned char
            public byte RTR;

            /// unsigned char
            public byte sz;

            /// unsigned char
            public byte stat;

            /// unsigned short
            public ushort STD_ID;

            /// unsigned char[8]
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
            public byte[] data;
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct mctrl_i2c_str
        {

            /// unsigned char
            public byte slave_id;

            /// unsigned char
            public byte sz;

            /// unsigned char[32]
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
            public string data;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct mctrl_gps_t
        {

            /// unsigned char
            public byte YY;

            /// unsigned char
            public byte MM;

            /// unsigned char
            public byte DD;

            /// unsigned char
            public byte reserv1;

            /// unsigned char
            public byte hh;

            /// unsigned char
            public byte mm;

            /// unsigned char
            public byte ss;

            /// unsigned char
            public byte reserv2;

            /// int
            public int la_deg;

            /// int
            public int lo_deg;

            /// unsigned char
            public byte GPS_qlty;

            /// unsigned char
            public byte sat_cnt;

            /// unsigned short
            public ushort HDOP;

            /// unsigned short
            public ushort speed;

            /// unsigned short
            public ushort course;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct mctrl_hd_str
        {

            /// u_char->unsigned char
            public byte ver;

            /// u_char->unsigned char
            public byte msg_no;

            /// u_char->unsigned char
            public byte d_id;

            /// u_char->unsigned char
            public byte stat;
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct mctrl_dt_t
        {

            /// mctrl_hd_t->mctrl_hd_str
            public mctrl_hd_str hd;

            /// char[36]
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 36)]
            public string dt;
        }

        public partial class NativeMethods
        {

            /// Return Type: void
            ///host_ip: char*
            ///hwnd: HWND->HWND__*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_init", CallingConvention = CallingConvention.StdCall)]
            public static extern void init(string host_ip, System.IntPtr hwnd);


            /// Return Type: void
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_close", CallingConvention = CallingConvention.StdCall)]
            public static extern void close();


            /// Return Type: void
            ///buf: void*
            ///sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_set_ctrl", CallingConvention = CallingConvention.StdCall)]
            public static extern void set_ctrl(System.IntPtr buf, int sz);


            /// Return Type: void
            ///buf: void*
            ///buf_sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_sens", CallingConvention = CallingConvention.StdCall)]
            public static extern void get_sens(INP_DT_STR[] buf, int buf_sz);


            /// Return Type: void
            ///no: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_chg_camera", CallingConvention = CallingConvention.StdCall)]
            public static extern void chg_camera(int no);


            /// Return Type: unsigned int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_JF_get_stamp", CallingConvention = CallingConvention.StdCall)]
            public static extern ulong JF_get_stamp();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Get_Wlink", CallingConvention = CallingConvention.StdCall)]
            public static extern int Get_Wlink();


            /// Return Type: int
            ///no: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Get_stat", CallingConvention = CallingConvention.StdCall)]
            public static extern int Get_stat(int no);


            /// Return Type: void
            ///host_ip: char*
            ///hwnd: HWND->HWND__*
            ///req: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_init_ex", CallingConvention = CallingConvention.StdCall)]
            public static extern void init_ex(System.IntPtr host_ip, System.IntPtr hwnd, int req);


            /// Return Type: int
            ///buf: void*
            ///buf_sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_jpeg", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_jpeg(System.IntPtr buf, int buf_sz);


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_vspeed", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_vspeed();


            /// Return Type: int
            ///req: int
            ///w_time: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_set_com_req", CallingConvention = CallingConvention.StdCall)]
            public static extern int set_com_req(int req, int w_time);


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_com_req", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_com_req();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_com_stat", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_com_stat();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_com_ver", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_com_ver();


            /// Return Type: void
            ///type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_set_video_inf", CallingConvention = CallingConvention.StdCall)]
            public static extern void set_video_inf(int type);


            /// Return Type: void
            ///speed: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_set_vspeed", CallingConvention = CallingConvention.StdCall)]
            public static extern void set_vspeed(int speed);


            /// Return Type: void*
            ///wait_flg: int
            ///wait_time: int
            ///dwBytesRead: int*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_jpeg_file", CallingConvention = CallingConvention.StdCall)]
            public static extern System.IntPtr get_jpeg_file(int wait_flg, int wait_time, ref int dwBytesRead);


            /// Return Type: void
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_free_jpeg_file", CallingConvention = CallingConvention.StdCall)]
            public static extern void free_jpeg_file();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Get_dtime", CallingConvention = CallingConvention.StdCall)]
            public static extern int Get_dtime();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Get_Staytime", CallingConvention = CallingConvention.StdCall)]
            public static extern int Get_Staytime();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_com_mode", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_com_mode();


            /// Return Type: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_get_cam_no", CallingConvention = CallingConvention.StdCall)]
            public static extern int get_cam_no();


            /// Return Type: int
            ///no: int
            ///buf: mctrl_can_t*
            ///sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Send_CANdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Send_CANdata(int no, ref CanMessage buf, int sz);


            /// Return Type: int
            ///no: int
            ///buf: mctrl_can_t*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Recv_CANdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Recv_CANdata(int no, ref CanMessage buf);


            /// Return Type: int
            ///no: int
            ///buf: char*
            ///slave_id: int
            ///sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Send_I2Cdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Send_I2Cdata(int no, System.IntPtr buf, int slave_id, int sz);


            /// Return Type: int
            ///no: int
            ///slave_id: int
            ///sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Req_Recv_I2Cdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Req_Recv_I2Cdata(int no, int slave_id, int sz);


            /// Return Type: int
            ///no: int
            ///buf: char*
            ///slave_id: int*
            ///sz: int*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Recv_I2Cdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Recv_I2Cdata(int no, System.IntPtr buf, ref int slave_id, ref int sz);


            /// Return Type: int
            ///no: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Req_Recv_PIdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Req_Recv_PIdata(int no);


            /// Return Type: int
            ///no: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Req_Reset_PIdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Req_Reset_PIdata(int no);


            /// Return Type: int
            ///no: int
            ///buf: inp_pi_dt_t*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Recv_PIdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Recv_PIdata(int no, ref INP_PI_DT_STR buf);


            /// Return Type: void
            ///fps: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_set_video_fps", CallingConvention = CallingConvention.StdCall)]
            public static extern void set_video_fps(int fps);


            /// Return Type: int
            ///no: int
            ///buf: mctrl_dt_t*
            ///sz: int
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Send_CMDdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Send_CMDdata(int no, ref mctrl_dt_t buf, int sz);


            /// Return Type: int
            ///no: int
            ///buf: mctrl_dt_t*
            [DllImport("TPJT3.dll", EntryPoint = "TPJT_Recv_RESdata", CallingConvention = CallingConvention.StdCall)]
            public static extern int Recv_RESdata(int no, ref mctrl_dt_t buf);

        }

    }
}
