//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wimm {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class GeneralSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneralSetting defaultInstance = ((GeneralSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneralSetting())));
        
        public static GeneralSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedControllerIndex {
            get {
                return ((int)(this["SelectedControllerIndex"]));
            }
            set {
                this["SelectedControllerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableQRDetection {
            get {
                return ((bool)(this["EnableQRDetection"]));
            }
            set {
                this["EnableQRDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ControlPeriodicWorkInterval {
            get {
                return ((int)(this["ControlPeriodicWorkInterval"]));
            }
            set {
                this["ControlPeriodicWorkInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetHighPriorityToPeriodicWork {
            get {
                return ((bool)(this["SetHighPriorityToPeriodicWork"]));
            }
            set {
                this["SetHighPriorityToPeriodicWork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ControlInterval {
            get {
                return ((int)(this["ControlInterval"]));
            }
            set {
                this["ControlInterval"] = value;
            }
        }
    }
}
