//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wimm {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    public sealed partial class GeneralSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneralSetting defaultInstance = ((GeneralSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneralSetting())));
        
        public static GeneralSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.200")]
        public string Tpip3_IP_Address {
            get {
                return ((string)(this["Tpip3_IP_Address"]));
            }
            set {
                this["Tpip3_IP_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedControllerIndex {
            get {
                return ((int)(this["SelectedControllerIndex"]));
            }
            set {
                this["SelectedControllerIndex"] = value;
            }
        }
    }
}
